import { IconElementData } from "../components/main/icons/icons";

export const iconsData: IconElementData[] = [
    { name: "Accordion", code: "accordion", category: "controls" },
    { name: "Album", code: "album", category: "controls" },
    { name: "Arrow down", code: "arrow_down", category: "navigation" },
    { name: "Arrow left", code: "arrow_left", category: "navigation" },
    { name: "Arrow right", code: "arrow_right", category: "navigation" },
    { name: "Arrow up", code: "arrow_up", category: "navigation" },
    { name: "Backward", code: "backward", category: "navigation" },
    { name: "Bag", code: "bag", category: "all" },
    { name: "Ban 2", code: "ban_2", category: "all" },
    { name: "Ban", code: "ban", category: "all" },
    { name: "Base", code: "base", category: "all" },
    { name: "Battery empty", code: "battery_empty", category: "controls" },
    { name: "Battery low", code: "battery_low", category: "controls" },
    { name: "Battery medium", code: "battery_medium", category: "controls" },
    { name: "Battery", code: "battery", category: "controls" },
    { name: "Bell", code: "bell", category: "controls" },
    { name: "Bookmark", code: "bookmark", category: "controls" },
    { name: "Calendar", code: "calendar", category: "controls" },
    { name: "Calendar 2", code: "calendar_2", category: "controls" },
    { name: "Calendar 3", code: "calendar_3", category: "controls" },
    { name: "Camera", code: "camera", category: "controls" },
    { name: "Card", code: "card", category: "controls" },
    { name: "Cart", code: "cart", category: "controls" },
    { name: "Cast", code: "cast", category: "controls" },
    { name: "Checkmark", code: "checkmark", category: "controls" },
    { name: "Chevron down", code: "chevron_down", category: "navigation" },
    { name: "Chevron left", code: "chevron_left", category: "navigation" },
    { name: "Chevron right", code: "chevron_right", category: "navigation" },
    { name: "Chevron up", code: "chevron_up", category: "navigation" },
    { name: "Chevron small down", code: "chevron_small_down", category: "navigation" },
    { name: "Chevron small left", code: "chevron_small_left", category: "navigation" },
    { name: "Chevron small right", code: "chevron_small_right", category: "navigation" },
    { name: "Chevron small up", code: "chevron_small_up", category: "navigation" },
    { name: "Clear", code: "clear", category: "controls" },
    { name: "Clock", code: "clock", category: "controls" },
    { name: "Close", code: "close", category: "controls" },
    { name: "Close small", code: "close_small", category: "controls" },
    { name: "Code", code: "code", category: "controls" },
    { name: "Comment 2", code: "comment_2", category: "editor" },
    { name: "Comment 3", code: "comment_3", category: "editor" },
    { name: "Comment 4", code: "comment_4", category: "editor" },
    { name: "Comment 5", code: "comment_5", category: "editor" },
    { name: "Comment", code: "comment", category: "editor" },
    { name: "Copy", code: "copy", category: "controls" },
    { name: "Credit", code: "credit", category: "controls" },
    { name: "Christmas tree", code: "christmas_tree", category: "all" },
    { name: "Cursor", code: "cursor", category: "controls" },
    { name: "Devices desktop", code: "devices_desktop", category: "devices" },
    { name: "Devices laptop", code: "devices_laptop", category: "devices" },
    { name: "Devices phone_2", code: "devices_phone_2", category: "devices" },
    { name: "Devices phone", code: "devices_phone", category: "devices" },
    { name: "Devices tablet_2", code: "devices_tablet_2", category: "devices" },
    { name: "Devices tablet", code: "devices_tablet", category: "devices" },
    { name: "Devices tv", code: "devices_tv", category: "devices" },
    { name: "Devices watch", code: "devices_watch", category: "devices" },
    { name: "Download", code: "download", category: "files" },
    { name: "Dumbbell", code: "dumbbell", category: "social" },
    { name: "Dumbbell 2", code: "dumbbell_2", category: "social" },
    { name: "Edit", code: "edit", category: "controls" },
    { name: "Emoji blink", code: "emoji_blink", category: "editor" },
    { name: "Emoji sad", code: "emoji_sad", category: "editor" },
    { name: "Emoji smile", code: "emoji_smile", category: "editor" },
    { name: "Error", code: "error", category: "signal" },
    { name: "Expand", code: "expand", category: "controls" },
    { name: "Facebook_2", code: "facebook_2", category: "social" },
    { name: "Facebook", code: "facebook", category: "social" },
    { name: "Feed", code: "feed", category: "social" },
    { name: "File 2", code: "file_2", category: "files" },
    { name: "File calc", code: "file_calc", category: "files" },
    { name: "File doc", code: "file_doc", category: "files" },
    { name: "File text", code: "file_text", category: "files" },
    { name: "File", code: "file", category: "files" },
    { name: "Folder", code: "folder", category: "files" },
    { name: "Forward", code: "forward", category: "navigation" },
    { name: "Future", code: "future", category: "navigation" },
    { name: "Gift", code: "gift", category: "all" },
    { name: "Git_fork", code: "git_fork", category: "social" },
    { name: "Git", code: "git", category: "social" },
    { name: "Globe", code: "globe", category: "social" },
    { name: "Grid", code: "grid", category: "editor" },
    { name: "Hashtag", code: "hashtag", category: "social" },
    { name: "Hashtag_2", code: "hashtag_2", category: "social" },
    { name: "Heart", code: "heart", category: "social" },
    { name: "Heartbeat", code: "heartbeat", category: "social" },
    { name: "History", code: "history", category: "controls" },
    { name: "Home 2", code: "home_2", category: "controls" },
    { name: "Home 3", code: "home_3", category: "controls" },
    { name: "Home 4", code: "home_4", category: "controls" },
    { name: "Home", code: "home", category: "controls" },
    { name: "Indicator 2", code: "indicator_2", category: "controls" },
    { name: "Indicator 3", code: "indicator_3", category: "controls" },
    { name: "Indicator", code: "indicator", category: "controls" },
    { name: "Info", code: "info", category: "signal" },
    { name: "Layer", code: "layer", category: "controls" },
    { name: "Leaf", code: "leaf", category: "all" },
    { name: "Link", code: "link", category: "controls" },
    { name: "List", code: "list", category: "editor" },
    { name: "Location 2", code: "location_2", category: "controls" },
    { name: "Location", code: "location", category: "controls" },
    { name: "Lock", code: "lock", category: "accounts" },
    { name: "Log in", code: "log_in", category: "accounts" },
    { name: "Log out", code: "log_out", category: "accounts" },
    { name: "Mail", code: "mail", category: "controls" },
    { name: "Media backward", code: "media_backward", category: "media" },
    { name: "Media forward", code: "media_forward", category: "media" },
    { name: "Media pause", code: "media_pause", category: "media" },
    { name: "Media play", code: "media_play", category: "media" },
    { name: "Media stop", code: "media_stop", category: "media" },
    { name: "Menu 2 reverted", code: "menu_2_reverted", category: "navigation" },
    { name: "Menu 2", code: "menu_2", category: "navigation" },
    { name: "Menu", code: "menu", category: "navigation" },
    { name: "Microphone", code: "microphone", category: "media" },
    { name: "Minus", code: "minus", category: "all" },
    { name: "More 2 vertical", code: "more_2_vertical", category: "navigation" },
    { name: "More 2", code: "more_2", category: "navigation" },
    { name: "More Vertical", code: "more_vertical", category: "navigation" },
    { name: "More", code: "more", category: "navigation" },
    { name: "Network", code: "network", category: "controls" },
    { name: "News", code: "news", category: "controls" },
    { name: "Note", code: "note", category: "editor" },
    { name: "Object bottom", code: "object_bottom", category: "editor" },
    { name: "Object center", code: "object_center", category: "editor" },
    { name: "Object fit", code: "object_fit", category: "editor" },
    { name: "Object left", code: "object_left", category: "editor" },
    { name: "Object middle", code: "object_middle", category: "editor" },
    { name: "Object right", code: "object_right", category: "editor" },
    { name: "Object top", code: "object_top", category: "editor" },
    { name: "Off", code: "off", category: "accounts" },
    { name: "Pencil", code: "pencil", category: "editor" },
    { name: "Phone", code: "phone", category: "controls" },
    { name: "Picture", code: "picture", category: "controls" },
    { name: "Pipe", code: "pipe", category: "editor" },
    { name: "Plus", code: "plus", category: "editor" },
    { name: "Printer", code: "printer", category: "controls" },
    { name: "Refresh", code: "refresh", category: "navigation" },
    { name: "Refresh base", code: "refresh_base", category: "navigation" },
    { name: "Rss", code: "rss", category: "controls" },
    { name: "search", code: "search", category: "controls" },
    { name: "server", code: "server", category: "controls" },
    { name: "Settings", code: "settings", category: "controls" },
    { name: "Setup", code: "setup", category: "controls" },
    { name: "Share 2", code: "share_2", category: "controls" },
    { name: "Share", code: "share", category: "controls" },
    { name: "Shrink", code: "shrink", category: "controls" },
    { name: "Social 2", code: "social_2", category: "social" },
    { name: "Social google", code: "social_google", category: "social" },
    { name: "Social instagram", code: "social_instagram", category: "social" },
    { name: "Social linkedin", code: "social_linkedin", category: "social" },
    { name: "Social twitter", code: "social_twitter", category: "social" },
    { name: "Social whatsup", code: "social_whatsup", category: "social" },
    { name: "Social youtube", code: "social_youtube", category: "social" },
    { name: "Social", code: "social", category: "social" },
    { name: "Speaker 2", code: "speaker_2", category: "media" },
    { name: "Speaker", code: "speaker", category: "media" },
    // { name: "Spinner cricle", code: "spinner_cricle", category: "all" },
    // { name: "Spinner cricle 2", code: "spinner_cricle_two", category: "all" },
    { name: "Star", code: "star", category: "social" },
    { name: "Stretch", code: "stretch", category: "editor" },
    { name: "Table", code: "table", category: "editor" },
    { name: "Text center", code: "text_center", category: "editor" },
    { name: "Text cursor", code: "text_cursor", category: "editor" },
    { name: "Text justify", code: "text_justify", category: "editor" },
    { name: "Text left", code: "text_left", category: "editor" },
    { name: "Text list", code: "text_list", category: "editor" },
    { name: "Text right", code: "text_right", category: "editor" },
    { name: "Thumb down", code: "thumb_down", category: "social" },
    { name: "Thumb up", code: "thumb_up", category: "social" },
    { name: "Trash", code: "trash", category: "controls" },
    { name: "Triangle down", code: "triangle_down", category: "navigation" },
    { name: "Triangle left", code: "triangle_left", category: "navigation" },
    { name: "Triangle right", code: "triangle_right", category: "navigation" },
    { name: "Triangle up", code: "triangle_up", category: "navigation" },
    { name: "Unlock", code: "unlock", category: "accounts" },
    { name: "Upload", code: "upload", category: "files" },
    { name: "User", code: "user", category: "users" },
    { name: "Users", code: "users", category: "users" },
    { name: "Volume down", code: "volume_down", category: "media" },
    { name: "Volume muted", code: "volume_muted", category: "media" },
    { name: "Volume up", code: "volume_up", category: "media" },
    { name: "Warning", code: "warning", category: "signal" },
    { name: "Window", code: "window", category: "controls" },
    { name: "Wireless", code: "wireless", category: "controls" },
    { name: "Sun", code: "sun", category: "all" },
    { name: "Moon", code: "moon", category: "all" },
    { name: "Moon 2", code: "moon_2", category: "all" },
    { name: "Light mode", code: "light_mode", category: "controls" },
    { name: "Sunny", code: "weather_sunny", category: "weather" },
    { name: "Partially sunny", code: "weather_sunny_partially", category: "weather" },
    { name: "Wind", code: "weather_wind", category: "weather" },
    { name: "Cloudy", code: "weather_cloudy", category: "weather" },
    { name: "Rainy", code: "weather_rainy", category: "weather" },
    { name: "Foggy", code: "weather_foggy", category: "weather" },
    { name: "Fog", code: "weather_fog", category: "weather" },
    { name: "Snowy", code: "weather_snowy", category: "weather" },
    { name: "Bolt", code: "bolt", category: "weather" },
    { name: "Cloud", code: "cloud", category: "controls" },
    { name: "Cloud offline", code: "cloud_offline", category: "controls" },
    { name: "Cookie", code: "cookie", category: "all" },
    { name: "Viewfinder", code: "viewfinder", category: "media" },
    { name: "Send", code: "send", category: "controls" },
    { name: "Send out", code: "send_out", category: "controls" },
    { name: "Wrench", code: "wrench", category: "controls" },
    { name: "Clip", code: "clip", category: "editor" },
    { name: "Clip 2", code: "clip_2", category: "editor" },
    { name: "Clip 3", code: "clip_3", category: "editor" },
    { name: "Stopwatch", code: "stopwatch", category: "media" },

]